-- Learning Hub initial Supabase schema.
-- Run with `supabase db push` or paste into the Supabase SQL editor.

create extension if not exists citext with schema extensions;

create table public.roles (
  id smallint primary key,
  code text not null unique,
  name text not null unique
);

create table public.divisions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.features (
  code text primary key,
  name text not null,
  description text not null default ''
);

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  legacy_id bigint generated by default as identity unique not null,
  username extensions.citext not null unique,
  full_name text not null default '',
  display_name text not null default '',
  bio text not null default '',
  hobby text not null default '',
  nik text not null default '',
  address text not null default '',
  phone text not null default '',
  contact_email text not null default '',
  education text not null default '',
  avatar_path text,
  video_path text,
  division_id bigint references public.divisions(id) on delete set null,
  role_id smallint not null default 4 references public.roles(id),
  account_status text not null default 'active'
    check (account_status in ('active', 'blocked', 'departed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint username_format check (username::text ~ '^[a-z0-9._-]+$')
);

create table public.role_permissions (
  role_id smallint not null references public.roles(id) on delete cascade,
  feature_code text not null references public.features(code) on delete cascade,
  allowed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (role_id, feature_code)
);

create table public.user_permissions (
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  feature_code text not null references public.features(code) on delete cascade,
  allowed boolean not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, feature_code)
);

create table public.zodiac_records (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(user_id) on delete cascade,
  day smallint not null check (day between 1 and 31),
  month smallint not null check (month between 1 and 12),
  zodiac_name text not null,
  date_range text not null,
  character text not null default '',
  strengths text not null default '',
  weaknesses text not null default '',
  compatible text not null default '',
  less_compatible text not null default '',
  element text not null default '',
  symbol text not null default '',
  accent_value bigint not null default 4279381363,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  quiz_code text not null,
  correct_count integer not null check (correct_count >= 0),
  total_count integer not null check (total_count > 0),
  answers jsonb not null default '[]'::jsonb,
  completed_at timestamptz not null default now(),
  check (correct_count <= total_count)
);

create table public.polls (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  question text not null,
  is_active boolean not null default true,
  created_by uuid references public.profiles(user_id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.poll_options (
  id uuid primary key default gen_random_uuid(),
  poll_id uuid not null references public.polls(id) on delete cascade,
  label text not null,
  position smallint not null default 0,
  unique (poll_id, label),
  unique (poll_id, id)
);

create table public.poll_votes (
  poll_id uuid not null references public.polls(id) on delete cascade,
  option_id uuid not null,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (poll_id, user_id),
  foreign key (poll_id, option_id)
    references public.poll_options(poll_id, id) on delete cascade
);

insert into public.roles (id, code, name) values
  (1, 'admin', 'Admin'),
  (2, 'supervisor', 'Supervisor'),
  (3, 'staf_customer', 'Staf Customer'),
  (4, 'customer', 'Customer')
on conflict (id) do update set code = excluded.code, name = excluded.name;

insert into public.divisions (code, name) values ('GEN', 'General')
on conflict (code) do update set name = excluded.name;

insert into public.features (code, name) values
  ('profile', 'Profile'),
  ('quiz', 'Quiz'),
  ('multi_quiz', 'Multi Quiz'),
  ('calculator', 'Calculator'),
  ('max_min', 'Max & Min'),
  ('discount', 'Discount'),
  ('bilangan', 'Bilangan'),
  ('sorting', 'Sorting'),
  ('polling', 'Polling'),
  ('zodiac', 'Zodiac'),
  ('create_account', 'Create Account'),
  ('view_all_profiles', 'Browse Profiles'),
  ('access_control', 'Access Control')
on conflict (code) do update set name = excluded.name;

insert into public.role_permissions (role_id, feature_code, allowed)
select role_id, feature_code, allowed
from (values
  (1, 'profile', true), (1, 'quiz', true), (1, 'multi_quiz', true),
  (1, 'calculator', true), (1, 'max_min', true), (1, 'discount', true),
  (1, 'bilangan', true), (1, 'sorting', true), (1, 'polling', true),
  (1, 'zodiac', true), (1, 'create_account', true),
  (1, 'view_all_profiles', true), (1, 'access_control', true),
  (2, 'profile', true), (2, 'quiz', true), (2, 'multi_quiz', true),
  (2, 'calculator', true), (2, 'max_min', true), (2, 'discount', true),
  (2, 'bilangan', true), (2, 'sorting', true), (2, 'polling', true),
  (2, 'zodiac', true), (2, 'create_account', false),
  (2, 'view_all_profiles', false), (2, 'access_control', false),
  (3, 'profile', true), (3, 'quiz', true), (3, 'multi_quiz', false),
  (3, 'calculator', true), (3, 'max_min', false), (3, 'discount', true),
  (3, 'bilangan', true), (3, 'sorting', false), (3, 'polling', false),
  (3, 'zodiac', true), (3, 'create_account', false),
  (3, 'view_all_profiles', false), (3, 'access_control', false),
  (4, 'profile', true), (4, 'quiz', true), (4, 'multi_quiz', false),
  (4, 'calculator', false), (4, 'max_min', false), (4, 'discount', false),
  (4, 'bilangan', false), (4, 'sorting', false), (4, 'polling', true),
  (4, 'zodiac', true), (4, 'create_account', false),
  (4, 'view_all_profiles', false), (4, 'access_control', false)
) as defaults(role_id, feature_code, allowed)
on conflict (role_id, feature_code) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger role_permissions_set_updated_at before update on public.role_permissions
for each row execute function public.set_updated_at();
create trigger user_permissions_set_updated_at before update on public.user_permissions
for each row execute function public.set_updated_at();
create trigger zodiac_records_set_updated_at before update on public.zodiac_records
for each row execute function public.set_updated_at();

create or replace function public.has_feature(requested_feature text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select up.allowed
       from public.user_permissions up
      where up.user_id = auth.uid() and up.feature_code = requested_feature),
    (select rp.allowed
       from public.role_permissions rp
       join public.profiles p on p.role_id = rp.role_id
      where p.user_id = auth.uid()
        and p.account_status = 'active'
        and rp.feature_code = requested_feature),
    false
  );
$$;

revoke all on function public.has_feature(text) from public;
grant execute on function public.has_feature(text) to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  general_division_id bigint;
  new_username text;
begin
  select id into general_division_id from public.divisions where code = 'GEN';
  new_username := lower(coalesce(
    nullif(new.raw_user_meta_data ->> 'username', ''),
    split_part(new.email, '@', 1)
  ));

  insert into public.profiles (
    user_id, username, full_name, display_name, division_id, role_id
  ) values (
    new.id,
    new_username,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', ''),
    general_division_id,
    4
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.protect_profile_security_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() = old.user_id and not public.has_feature('access_control') then
    new.role_id = old.role_id;
    new.account_status = old.account_status;
    new.username = old.username;
  end if;
  return new;
end;
$$;

create trigger profiles_protect_security_fields
before update on public.profiles
for each row execute function public.protect_profile_security_fields();

alter table public.roles enable row level security;
alter table public.divisions enable row level security;
alter table public.features enable row level security;
alter table public.profiles enable row level security;
alter table public.role_permissions enable row level security;
alter table public.user_permissions enable row level security;
alter table public.zodiac_records enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.polls enable row level security;
alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;

create policy "authenticated can read roles" on public.roles
for select to authenticated using (true);
create policy "authenticated can read divisions" on public.divisions
for select to authenticated using (true);
create policy "admins manage divisions" on public.divisions
for all to authenticated using (public.has_feature('access_control'))
with check (public.has_feature('access_control'));
create policy "authenticated can read features" on public.features
for select to authenticated using (true);

create policy "profiles are self or browseable" on public.profiles
for select to authenticated using (
  user_id = auth.uid() or public.has_feature('view_all_profiles')
);
create policy "profiles updated by owner or admin" on public.profiles
for update to authenticated using (
  (user_id = auth.uid() and account_status = 'active')
  or public.has_feature('access_control')
) with check (
  (user_id = auth.uid() and account_status = 'active')
  or public.has_feature('access_control')
);

create policy "authenticated can read role permissions" on public.role_permissions
for select to authenticated using (true);
create policy "admins insert role permissions" on public.role_permissions
for insert to authenticated with check (public.has_feature('access_control'));
create policy "admins update role permissions" on public.role_permissions
for update to authenticated using (public.has_feature('access_control'))
with check (public.has_feature('access_control'));
create policy "admins delete role permissions" on public.role_permissions
for delete to authenticated using (public.has_feature('access_control'));

create policy "users read own permission overrides" on public.user_permissions
for select to authenticated using (
  user_id = auth.uid() or public.has_feature('access_control')
);
create policy "admins manage permission overrides" on public.user_permissions
for all to authenticated using (public.has_feature('access_control'))
with check (public.has_feature('access_control'));

create policy "owners read zodiac records" on public.zodiac_records
for select to authenticated using (
  owner_id = auth.uid() and public.has_feature('zodiac')
);
create policy "owners insert zodiac records" on public.zodiac_records
for insert to authenticated with check (
  owner_id = auth.uid() and public.has_feature('zodiac')
);
create policy "owners update zodiac records" on public.zodiac_records
for update to authenticated using (
  owner_id = auth.uid() and public.has_feature('zodiac')
) with check (
  owner_id = auth.uid() and public.has_feature('zodiac')
);
create policy "owners delete zodiac records" on public.zodiac_records
for delete to authenticated using (
  owner_id = auth.uid() and public.has_feature('zodiac')
);

alter publication supabase_realtime add table public.zodiac_records;

create policy "users read own quiz attempts" on public.quiz_attempts
for select to authenticated using (
  user_id = auth.uid() and public.has_feature('quiz')
);
create policy "users insert own quiz attempts" on public.quiz_attempts
for insert to authenticated with check (
  user_id = auth.uid() and public.has_feature('quiz')
);

create policy "active polls are readable" on public.polls
for select to authenticated using (
  (is_active and public.has_feature('polling'))
  or public.has_feature('access_control')
);
create policy "admins manage polls" on public.polls
for all to authenticated using (public.has_feature('access_control'))
with check (public.has_feature('access_control'));
create policy "poll options are readable" on public.poll_options
for select to authenticated using (public.has_feature('polling'));
create policy "admins manage poll options" on public.poll_options
for all to authenticated using (public.has_feature('access_control'))
with check (public.has_feature('access_control'));
create policy "votes are readable" on public.poll_votes
for select to authenticated using (public.has_feature('polling'));
create policy "users insert own vote" on public.poll_votes
for insert to authenticated with check (
  user_id = auth.uid() and public.has_feature('polling')
);
create policy "users update own vote" on public.poll_votes
for update to authenticated using (
  user_id = auth.uid() and public.has_feature('polling')
) with check (
  user_id = auth.uid() and public.has_feature('polling')
);
create policy "users delete own vote" on public.poll_votes
for delete to authenticated using (
  user_id = auth.uid() and public.has_feature('polling')
);

insert into storage.buckets (id, name, public)
values ('profile-media', 'profile-media', false)
on conflict (id) do nothing;

create policy "users read permitted profile media" on storage.objects
for select to authenticated using (
  bucket_id = 'profile-media' and (
    (
      (storage.foldername(name))[1] = auth.uid()::text
      and public.has_feature('profile')
    )
    or public.has_feature('view_all_profiles')
  )
);
create policy "users upload own profile media" on storage.objects
for insert to authenticated with check (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.has_feature('profile')
);
create policy "users update own profile media" on storage.objects
for update to authenticated using (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.has_feature('profile')
) with check (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.has_feature('profile')
);
create policy "users delete own profile media" on storage.objects
for delete to authenticated using (
  bucket_id = 'profile-media'
  and (storage.foldername(name))[1] = auth.uid()::text
  and public.has_feature('profile')
);
